version: '3'
services:
  weechat:
    image: hubbeking/weechat
    container_name: weechat
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 9001:9001
    volumes:
      - ./weechat:/home/weechat/.weechat
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
