version: '3'
services:
  weechat:
    image: captainspam/weechat
    build:
      context: .
    container_name: weechat
    restart: unless-stopped
    ports:
      - 8002:8002
    volumes:
      - ./weechat/:/home/weechat/.weechat/
      - ./tmux.conf:/home/weechat/.tmux.conf
